name: delivery_apps
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: any
  flutter_bloc: ^7.2.0
  bottom_picker: ^2.0.4
  get_it: ^7.6.7
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10

  flutter_map: ^6.1.0
  flutter_map_marker_cluster: ^1.3.5
  flutter_map_animations: ^0.6.0
  flutter_map_location_marker: ^8.0.8
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  google_polyline_algorithm: ^3.1.0

  dio: ^5.4.3+1
  retrofit: ^4.0.3
  json_annotation: ^4.9.0

  theme_mode_handler: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^2.0.0
  retrofit_generator:  ^8.0.0
  json_serializable: ^6.6.2

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
